blog-service:
    url: http://localhost:8081
comment-service:
    url: http://localhost:8082

server:
  port: 8082
spring:
  application:
    name: comment-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/b?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: /
#logging:
#  level:
#    root: info
#    com.lrm: debug
#  file:
#    name: /tmp/blog-dev.log

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0

comment:
  touristAvatar: /images/touristAvatar.png
  userAvatar: /images/userAvatar.png


