blog-service:
    url: http://blog
#comment-service:
#    url: http://comment

server:
  port: 8082
spring:
  application:
    name: comment-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/k8sdb-comment?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: /
#logging:
#  level:
#    root: info
#    com.lrm: debug
#  file:
#    name: /tmp/blog-dev.log

#Eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    enabled: false
#Logging
logging:
  level:
    debug: DEBUG

# Actuator configuration
management:
  health:
    circuitBreaker:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Zipkin
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

comment:
  touristAvatar: /images/touristAvatar.png
  userAvatar: /images/userAvatar.png