server:
  port: 8084
spring:
  application:
    name: gateway
#Gateway

  cloud:
    gateway:
      routes:
        - id: blog-service
          uri: http://blog:8081
          predicates:
            - Path=/blog/**

        - id: comment-service
          #container_name
          uri: http://comment:8082
          predicates:
            - Path=/comment/**

        - id: eureka-service
          uri: http://service-registry:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-service-static
          uri: http://service-registry:8761
          predicates:
            - Path=/eureka/**
#          filters:
#            - StripPrefix=1
logging:
  level:
    root: info
    org:
        springframework:
            cloud:
              gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
#Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0