server:
  port: 8084
spring:
  application:
    name: gateway
#Gateway
  cloud:
    gateway:
      routes:
        - id: blog-service
          uri: lb://BLOG-SERVICE-DEV
          predicates:
            - Path=/blog/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comment/**

        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#          filters:
#            - StripPrefix=1
logging:
  level:
    root: info
    org:
        springframework:
            cloud:
              gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0