spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoRsk/application-config
          # run failed if uri doesn't be added
#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka